### ISSUE TITLE
期待代码开源！

### ISSUE THREAD

**Issue by tonglily** [qq456cvb/CPPF2#1]
感谢作者的工作！
想问一下什么时候会开源呢

**Comment by qq456cvb** [comment]
We will release the code by the end of Feb. or the start of March. Actually, this work can naturally be adapted to detect the joint axes or keypoints of articulated objects, and we have tested it on microwaves. Stay tuned and we will give a fantastic demo soon :).

**Comment by qq456cvb** [comment]
目前已开源了大部分代码，可以在NOCS数据集上训练和测试了
