### ISSUE TITLE
关于数据集处理

### ISSUE THREAD

**Issue by qingchenkanlu** [qq456cvb/CPPF2#4]
您好，感谢您开源您的工作，请问您是否能开源在Phocal数据集上的处理代码以及对应的dataset.py文件呢？非常感谢！

**Comment by qq456cvb** [comment]
Hi thanks for your interest, you can use the scripts `data/[phocal|wild6d]_convert2real275.py` to convert PhoCAL or Wild6D data into the same format of  NOCS REAL275.

**Comment by qingchenkanlu** [comment]
Thank you very much for your reply. It seems that the folder 'category_nocs' is not included in the open-source code. Looking forward to your future open-source releases to fill this gap.

**Comment by qq456cvb** [comment]
Hi qingchen, you can directly delete those lines in `phocal_convert2real275.py`, The `category_nocs` import is not used.

**Comment by qingchenkanlu** [comment]
OK, thanks!
